#!/bin/bash

cd $(dirname $0)
rsync --exclude-from=.gitignore \
    --exclude=.gitignore \
    --exclude=.git \
    --exclude=bootstrap \
    --exclude=README.md \
    -av . ~

if [[ ! -d ~/.emacs.d ]]; then
    git clone --recursive git@github.com:harto/emacs.d ~/.emacs.d
fi
