#!/usr/bin/env bash
set -euo pipefail

# Note: requires Homebrew (https://brew.sh)

packages=(
  aws-vault
  bash
  bash-completion
  chruby
  codemod
  git
  hub
  jq
  ripgrep
  ruby-install
  # dropbox
  firefox
)

for p in "${packages[@]}"; do
  brew install "$p"
done

brew install --cask emacs
