#!/usr/bin/env bash

set -exuo pipefail

HERE="$(cd "$(dirname "$0")"; pwd -P)"

# TODO:
# - set OS settings
#   - keyboard repeat rate
#   - remap caps lock

"$HERE"/install-packages
"$HERE"/symlink-dotfiles
"$HERE"/symlink-scripts
