#!/usr/bin/env bash

set -x

HERE="$(cd "$(dirname "$0")"; pwd -P)"

# TODO:
# - set OS settings
#   - keyboard repeat rate
#   - remap caps lock

( cd "$HERE" && brew bundle )

if [[ ! -d ~/.emacs.d ]]; then
  git clone git@github.com:harto/emacs.d ~/.emacs.d
fi

"$HERE"/symlink-dotfiles
"$HERE"/symlink-scripts
