#!/usr/bin/env bash

set -ex

HERE=$(cd "$(dirname "$0")"; pwd -P)

# TODO: this should probably do things like:
# set default OS X keyboard preferences (repeat rate, disable capslock)

#
# Homebrew packages
#

brew update
brew upgrade
brew tap Homebrew/bundle
cd "$HERE"
brew bundle
brew cleanup

#
# Install various scripts and dotfiles
#

"$HERE"/install-dotfiles
"$HERE"/install-scripts
