#!/usr/bin/env bash
set -euo pipefail

find "$(cd "$(dirname "$0")"/dotfiles; pwd -P)" -type f -print0 | \
  xargs -0 -t -n1 -I% ln -s % ~

if [[ ! -d ~/.emacs.d ]]; then
  git clone git@github.com:harto/emacs.d ~/.emacs.d
fi
